// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package nbdb

// Sample defines an object in Sample table
type Sample struct {
	UUID           string `ovsdb:"_uuid"`
	CollectorSetID int    `ovsdb:"collector_set_id"`
	ObsPointID     int    `ovsdb:"obs_point_id"`
	Probability    int    `ovsdb:"probability"`
}
